USE test;

DROP TABLE Comment;
CREATE TABLE Comment
(
	id INT PRIMARY KEY AUTO_INCREMENT,
    comment VARCHAR(2047) NOT NULL,
    memberId VARCHAR(255) NOT NULL,
    boardId INT NOT NULL,
    inserted TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (memberId) REFERENCES Member(id),
    FOREIGN KEY (boardId) REFERENCES Board(id)
);

SELECT * FROM Comment;
SELECT * FROM Board;
SELECT * FROM Member;

DESC Board;
DESC Member;

-- 테이블이 존재하면 DROP, 없으면 X
DROP TABLE IF EXISTS Comment;


SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  TABLE_SCHEMA = 'test' AND
  TABLE_NAME = 'Board';